yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path(
        'author/',
        views.AboutAuthorView.as_view(),
        name='author',
    ),
    path(
        'tech/',
        views.AboutTechView.as_view(),
        name='tech',
    ),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'


urlpatterns = [
    path('group/<slug:slug>/', views.group_list, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('', views.index, name='index'),
]

yatube/users/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from . import views


app_name = 'users'


urlpatterns = [
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup',
    ),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change',
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done',
    ),

    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset',
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done',
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm',
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete',
    ),
]

yatube/yatube/urls.py
from django.contrib import admin

from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts'))
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Название группы',
        help_text='Введите название группы',
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Адрес для страницы с группой',
        help_text='Адрес заполняется автоматически',
    )
    description = models.TextField(
        max_length=200,
        verbose_name='Описание',
        help_text='Укажите описание группы',
    )

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст сообщения',
        help_text='Введите текст сообщения',
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
        help_text='Дата публикации сообщения',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
        help_text='Автор, к которому будет относится сообщение',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относится сообщение',
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'

    def __str__(self):
        return self.text[:15]

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')
        help_texts = {
            'text': 'Введите текст сообщения',
            'group': 'Выберете группу',
        }
        labels = {
            'text': 'Текст сообщения',
            'group': 'Группа',
        }

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
        )

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from .models import Group, Post, User
from .utils import paginate_posts
from .forms import PostForm


def index(request):
    posts = Post.objects.select_related('author', 'group')
    page_obj = paginate_posts(request, posts)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_list(request, slug):
    group = get_object_or_404(Group, slug=slug)
    page_obj = paginate_posts(
        request,
        group.posts.all(),
    )
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    page_obj = paginate_posts(request, author.posts.all())
    count = author.posts.count()
    context = {
        'count': count,
        'author': author,
        'page_obj': page_obj,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    count = post.author.posts.count()
    context = {
        'count': count,
        'post': post,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    context = {
        'form': form,
    }
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author.username)
    return render(request, 'posts/post_create.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(request.POST or None, instance=post)
    context = {
        'form': form,
        'is_edit': True
    }
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    return render(request, 'posts/post_create.html', context)

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends 'base.html' %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
  <h1>Привет, я автор</h1>
  <p>
    Данный проект - моя кровь и боль. 
    Кучу времени я поратил, что бы разобраться в том или ином коде или строках, что бы всё это заработало. 
    Часто, очень часто, обращался за сторонней помощью и с точностью могу заявить одно - даже написания такого "легкого проекта" 
    результат работы не одного человека, а нескольких людей, которые мне в этом помогали. Огромное им спасибо. 
  </p>
{% endblock %} 

yatube/templates/about/tech.html
{% extends 'base.html' %}
{% block title %}Технологии{% endblock %}
{% block content %}
  <div class="row">
    <h1>Вот что я умею</h1>
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Python
        </li>
        <li class="list-group-item">
          Django
        </li>
        <li class="list-group-item">
          BootsTrap
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>Данные приложения помогали мне написать этот сайт.</p>
    </article>
  </div>
{% endblock %} 

yatube/templates/base.html
{% load static %}
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    {% include 'includes/header.html' %}
    <main>
      <div class="container py-5">
        {% block content %}
        {% endblock %}
      </div>
    </main>
    {% include 'includes/footer.html' %}    
  </body>
</html>

yatube/templates/includes/footer.html
<footer class="page-footer font-small blue border-top">
    <div class="footer-copyright text-center py-3">
      <p>
        © {{ year }} Copyright YaTube
        <span style="color:red">Ya</span>tube
      </p> 
    </div>
  </footer>

yatube/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img
          src="{% static 'img/logo.png'%}"
          width="30"
          height="30"
          class="d-inline-block align-top"
          alt=""
        />
        <span style="color: red">Ya</span>tube
      </a>
      {% with request.resolver_match.view_name as view_name %}
        <ul class="nav nav-pills">
            <li class="nav-item"> 
              <a class="nav-link
                {% if view_name  == 'posts:index' %} active {% endif %}"
                href="{% url 'posts:index' %}">
                Главная
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link
                {% if view_name  == 'about:author' %} active {% endif %}"
                href="{% url 'about:author' %}">
                Об авторе
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link
                {% if view_name  == 'about:tech' %} active {% endif %}"
                href="{% url 'about:tech' %}">
                Технологии
              </a>
            </li>
          {% if user.is_authenticated %}
            <li class="nav-item"> 
              <a class="nav-link
                {% if view_name  == 'posts:post_create' %} active {% endif %}"
                href="{% url 'posts:post_create' %}">
                Новая запись
              </a>
            </li>
            <li class="nav-item">
              <div class="dropdown">
                <button class="btn btn-link dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                  Пользователь: {{ user.username }}
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                  <li class="nav-item"> 
                    <a class="dropdown-item
                      {% if view_name  == 'users:password_change' %} active {% endif %}"
                      href="{% url 'users:password_change' %}">
                      Изменить пароль
                    </a>
                  </li>
                  <li class="nav-item"> 
                    <a class="dropdown-item" href="{% url 'users:logout' %}">
                      Выйти
                    </a>
                  </li>
                </ul>
              </div>
            </li>
          {% else %}
            <li class="nav-item"> 
              <a class="nav-link link-light" href="{% url 'users:login' %}">
                Войти
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light" href="{% url 'users:signup' %}">
                Регистрация
              </a>
            </li>
          {% endif %}
        </ul>
      {% endwith %}
    </div>
  </nav>
</header>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  Записи группы {{ group.title }}: {{ group.description }}
{% endblock %}
{% block content%}
  <h1>
    {{ group.title }}
  </h1>
  <p>
    {{ group.description }}
  </p>
  {% for post in page_obj %}
    {% include 'posts/includes/post.html' %}
    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/includes/form_new_post.html
{% include 'users/includes/form_error.html' %}
<form method="POST"
  {% if is_edit %}
    action="{% url 'posts:post_edit' form.instance.pk %}"
  {% else %}
    action="{% url 'posts:post_create' %}"
  {% endif %}>
  {% csrf_token %}
  {% include 'users/includes/form.html' %}
  <div class="d-flex justify-content-end">
    <button type="submit" class="btn btn-primary">
      {% if is_edit %}
        Сохранить
      {% else %}
        Добавить
      {% endif %}
    </button>
  </div>
</form>

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/includes/post.html
<article>
  <ul>
    <li>
      <a href="{% url 'posts:profile' post.author.username %}">
        Автор: {{ post.author.get_full_name }}
      </a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:'d E Y' }}
    </li>
  </ul>      
  <p>
    {{ post.text|linebreaksbr }}
  </p>
    <a href="{% url 'posts:post_detail' post.pk %}">
      подробная информация
    </a>
  {% if not group and post.group %}
    <br>
    <a href="{% url 'posts:group_list' post.group.slug %}">
      все записи группы
    </a>
  {% endif %}
</article>

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %} Последние обновления на сайте {% endblock %}
{% block content %}
  <h1>Последние обновления на сайте</h1>
  {% for post in page_obj %}
    {% include 'posts/includes/post.html' %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_create.html
{% extends 'base.html' %}
{% block title %}
{% if is_edit %}
  Редактировать пост
{% else %}
  Новый пост
{% endif %}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Редактировать пост
            {% else %}
              Новый пост
            {% endif %}
          </div>
          <div class="card-body">
            {% include 'posts/includes/form_new_post.html' %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
  Пост {{ post.text|truncatechars:30 }}
{% endblock %}
{% block content%}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:'d E Y' }}
        </li>
        {% if post.group %}
          <li class="list-group-item">
            <p>
              Группа:<br>
              {{ post.group.title }}<br>
              {{ post.group.description }}
            </p>
            <a href="{% url 'posts:group_list' post.group.slug %}">
              Все записи группы
            </a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: <span >{{ count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>
        {{ post.text|linebreaksbr }}
      </p>
      {% if post.author == user %}
      <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
        Редактировать
      </a>
      {% endif %}
    </article>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock %}
{% block content%}
  <div class="container py-5">
    <h1>
      Все посты пользователя {{ author.get_full_name }}
    </h1>
    <h3>
      Всего постов: {{ count }}
    </h3>
    {% for post in page_obj %}
    {% include 'posts/includes/post.html' %}
      {% if not forloop.last %}<hr>
      {% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/users/includes/form.html
{% load user_filters %}
{% for field in form %}
    <div class="form-group row my-3 p-3"
    {% if field.field.required %} 
      aria-required="true"
    {% else %}
      aria-required="false"
    {% endif %}
    >
      <label for="{{ field.id_for_label }}">
        {{ field.label }}
        {% if field.field.required %}
          <span class="required text-danger">*</span>
        {% endif %}
      </label>
      <div>
      {{ field|addclass:'form-control' }}
        {% if field.help_text %}
        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
          {{ field.help_text|safe }}
        </small>
        {% endif %}
      </div>
    </div>
{% endfor %}

yatube/templates/users/includes/form_error.html
{% if form.errors %}
{% for field in form %}
  {% for error in field.errors %}            
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
  <div class="alert alert-danger">
    {{ error|escape }}
  </div>
{% endfor %}
{% endif %}

yatube/templates/users/includes/form_group_class.html
<div class="form-group row my-3 p-3">
  <label for="id_new_password1">
      Новый пароль
      <span class="required text-danger">*</span>
  </label>    
  <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
    <small id="id_new_password1-help" class="form-text text-muted">
    <ul>
        <li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li>
        <li>Ваш пароль должен содержать как минимум 8 символов.</li>
        <li>Ваш пароль не может быть одним из широко распространённых паролей.</li>
        <li>Ваш пароль не может состоять только из цифр.</li>
    </ul>
    </small>
</div>
<div class="form-group row my-3 p-3">
  <label for="id_new_password2">
      Подтверждение нового пароля
      <span class="required text-danger">*</span>
  </label>    
  <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
</div>
<div class="col-md-6 offset-md-4">
  <button type="submit" class="btn btn-primary">
      Изменить пароль
  </button>
</div>

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}
  Вы вышли из системы
{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/login.html
{% extends 'base.html' %}
{% block title %}
  Войти
{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Войти на сайт
      </div>
      <div class="card-body">
        {% include 'users/includes/form_error.html' %}
        <form method="post"
          {% if action_url %}
            action="{% url 'action_url' %}"
          {% endif %}
        >
        {% csrf_token %}
        {% include 'users/includes/form.html' %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <a href="{% url 'users:password_reset' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %}
  Пароль изменён
{% endblock %}
{% block content %}
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Пароль изменён
              </div>
              <div class="card-body"> 
                <p>
                  Пароль изменён успешно
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}
  Изменение пароля
{% endblock %}
{% block content %}
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Изменить пароль
              </div>
              <div class="card-body">
                <form method="POST" action="{% url 'users:password_change' %}">
                  {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_old_password">
                      Старый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
                  </div>
                  {% include 'users/includes/form_group_class.html' %}
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% block title %}
  Сброс пароля прошёл успешно
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Восстановление пароля завершено
        </div>
        <div class="card-body">
          <p>Ваш пароль был сохранен. Используйте его для входа</p>
          <a href="{% url 'users:login' %}">
            войти
          </a>
        </div> 
      </div> 
    </div>
  </div> 
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% block title %}
  Новый пароль
{% endblock %}
{% block content %}
{% if validlink %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Введите новый пароль
        </div>
        <div class="card-body">
          <form method="post"
            {% if action_url %}
              action="{% url 'action_url' %}"
            {% endif %}
          >
            {% csrf_token %}
            {% include 'users/includes/form_group_class.html' %}
          </form>
        </div>
      </div>
    </div>
  </div>
{% else %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Ошибка</div>
        <div class="card-body">
          <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
        </div>
      </div>
    </div>
  </div>
{% endif %}
{% endblock %}

yatube/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block title %}
  Сброс пароля прошёл успешно
{% endblock %}
{% block content %}
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Отправлено письмо
              </div>
              <div class="card-body">
                <p>
                  Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля
                </p>
              </div> 
            </div> 
          </div>
        </div> 
      </div>
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends 'base.html' %}
{% block title %}
  Сброс пароля
{% endblock %}
{% block content %}
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Чтобы сбросить старый пароль — введите адрес электронной почты,
                под которым вы регистрировались
              </div>
              <div class="card-body"> 
                <form method="POST" action="{% url 'users:password_reset' %}">
                  {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_email">
                      Адрес электронной почты
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Сбросить пароль
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>  
      </div>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}
  Зарегистрироваться
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Зарегистрироваться
        </div>
          <div class="card-body">
            {% load user_filters %}
              {% include 'users/includes/form_error.html' %}
              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
              {% include 'users/includes/form.html' %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
  </div>
{% endblock %}